# Generated by Django 2.1.7 on 2019-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('actor_bio', models.TextField(blank=True, null=True)),
                ('actor_chname', models.CharField(blank=True, db_column='actor_chName', max_length=100, null=True)),
                ('actor_forename', models.CharField(blank=True, db_column='actor_foreName', max_length=100, null=True)),
                ('actor_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('actor_constellation', models.CharField(blank=True, max_length=100, null=True)),
                ('actor_birthplace', models.CharField(blank=True, db_column='actor_birthPlace', max_length=100, null=True)),
                ('actor_birthday', models.CharField(blank=True, db_column='actor_birthDay', max_length=100, null=True)),
                ('actor_repworks', models.CharField(blank=True, db_column='actor_repWorks', max_length=100, null=True)),
                ('actor_achiem', models.TextField(blank=True, null=True)),
                ('actor_brokerage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'actor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActorToMovie',
            fields=[
                ('actor_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'actor_to_movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_bio', models.TextField(blank=True, null=True)),
                ('movie_chname', models.CharField(blank=True, db_column='movie_chName', max_length=100, null=True)),
                ('movie_forename', models.CharField(blank=True, db_column='movie_foreName', max_length=100, null=True)),
                ('movie_prodtime', models.CharField(blank=True, db_column='movie_prodTime', max_length=100, null=True)),
                ('movie_prodcompany', models.CharField(blank=True, db_column='movie_prodCompany', max_length=100, null=True)),
                ('movie_director', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_screenwriter', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_star', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_length', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_releasetime', models.CharField(blank=True, db_column='movie_releaseTime', max_length=100, null=True)),
                ('movie_language', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_achiem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieToGenre',
            fields=[
                ('movie_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_to_genre',
                'managed': True,
            },
        ),
    ]
